version: "3.9"
services:
  clipystream-app:
    profiles: ["prod"]
    image: ghcr.io/trodix/clipystream:latest
    container_name: clipystream
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      APP_CORS_ORIGINS: "clipystream.com"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/clipystream"
      APP_REDIS_HOST: "redis"
      APP_STORAGE_PROVIDER_CLASS: "com.trodix.clipystream.provider.S3StorageProvider"
      S3_BUCKET_PROVIDER_SECRET_KEY:
      APP_STORAGE_PROVIDER_S3_ACCESS-KEY: "SCW09K8PC37FVC4MK2BD"
      APP_STORAGE_PROVIDER_S3_REGION: "fr-par"
      APP_STORAGE_PROVIDER_S3_ENDPOINT-BUCKET-URL: "https://s3.fr-par.scw.cloud"
      APP_STORAGE_PROVIDER_S3_BUCKET-NAME: "clipystream"
    volumes:
      - /var/log/clipystream:/opt/clipystream/logs
    links:
      - postgres
      - redis
  postgres:
    profiles: ["prod"]
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_DB: clipystream
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /opt/clipystream/data:/var/lib/postgresql/data

  redis:
    profiles: ["prod"]
    image: redis
    expose:
      - "6379"
    volumes:
      - /opt/clipystream/redis/conf:/usr/local/etc/redis

  redis-dev:
    profiles: ["dev"]
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - /opt/clipystream/redis/conf:/usr/local/etc/redis

# Matomo
  matomo-db:
    image: mariadb
    expose:
      - "3306"
    command: --max-allowed-packet=64MB
    volumes:
      - /opt/clipystream/matomo/data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - ./deployment/docker/matomo-db.env
  matomo-app:
    image: matomo:fpm-alpine
    links:
      - matomo-db
    volumes:
      - matomo_app_vol1:/var/www/html
      - /opt/clipystream/matomo/config:/var/www/html/config
    environment:
      PHP_MEMORY_LIMIT: 2048M
      MATOMO_DATABASE_HOST: matomo-db
    env_file:
      - ./deployment/docker/matomo-db.env

  matomo-proxy:
    image: nginx:alpine
    volumes:
      - matomo_app_vol1:/var/www/html:ro
      - ./deployment/docker/matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8001:80"

volumes:
  matomo_app_vol1:
